### ISSUE TITLE
re: email

### ISSUE THREAD

**Issue by DragoniteSpam** [Dreamer13sq/DmrVBM-blender-to-gms2#3]
Apparently my email just randomly refused to send a reply to yours, so that's fun. This looks pretty well made, even down to building the vertex format based on what's in the file. I don't use Blender much, but I can send it to a few people to see what they think if you want!

**Comment by Dreamer13sq** [comment]
Thanks for checking it out. I don't mind if you share the repo around. Any feedback is nice for when I return to work on it.
